{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "87c3cc37-a71d-499b-a665-0abab7031257",
   "metadata": {},
   "source": [
    "## Q1. Explain why we have to use the exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ecfa07d6-d616-4b05-8485-8e315c6b67a7",
   "metadata": {},
   "source": [
    "## ANS == \n",
    "When creating a custom exception in Python, it is important to use the Exception class as the base class for the new exception class that you define. This is because the Exception class is the built-in base class for all exceptions in Python, and provides a set of methods and attributes that are necessary for proper exception handling.\n",
    "\n",
    "By inheriting from the Exception class, your custom exception class will automatically inherit all the necessary attributes and methods required for proper exception handling. This includes the ability to capture and display detailed information about the exception, such as its type, message, traceback, and any additional context that might be useful for debugging purposes."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b33c8681-59d4-4157-98e7-2ce12e480d91",
   "metadata": {},
   "source": [
    "## Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8b063152-1c94-4cbd-94b4-be228f01a36c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ArithmeticError\n",
      "    FloatingPointError\n",
      "    OverflowError\n",
      "    ZeroDivisionError\n",
      "    DecimalException\n",
      "\n",
      "\n",
      "AssertionError\n",
      "\n",
      "\n",
      "AttributeError\n",
      "    FrozenInstanceError\n",
      "\n",
      "\n",
      "BlockingIOError\n",
      "\n",
      "\n",
      "BrokenPipeError\n",
      "\n",
      "\n",
      "BufferError\n",
      "\n",
      "\n",
      "ChildProcessError\n",
      "\n",
      "\n",
      "ConnectionAbortedError\n",
      "\n",
      "\n",
      "ConnectionError\n",
      "    BrokenPipeError\n",
      "    ConnectionAbortedError\n",
      "    ConnectionRefusedError\n",
      "    ConnectionResetError\n",
      "\n",
      "\n",
      "ConnectionRefusedError\n",
      "\n",
      "\n",
      "ConnectionResetError\n",
      "    RemoteDisconnected\n",
      "\n",
      "\n",
      "EOFError\n",
      "    IncompleteReadError\n",
      "\n",
      "\n",
      "EnvironmentError\n",
      "    ConnectionError\n",
      "    BlockingIOError\n",
      "    ChildProcessError\n",
      "    FileExistsError\n",
      "    FileNotFoundError\n",
      "    IsADirectoryError\n",
      "    NotADirectoryError\n",
      "    InterruptedError\n",
      "    PermissionError\n",
      "    ProcessLookupError\n",
      "    TimeoutError\n",
      "    UnsupportedOperation\n",
      "    itimer_error\n",
      "    herror\n",
      "    gaierror\n",
      "    SSLError\n",
      "    Error\n",
      "    SpecialFileError\n",
      "    ExecError\n",
      "    ReadError\n",
      "    URLError\n",
      "    BadGzipFile\n",
      "\n",
      "\n",
      "FileExistsError\n",
      "\n",
      "\n",
      "FileNotFoundError\n",
      "\n",
      "\n",
      "FloatingPointError\n",
      "\n",
      "\n",
      "IOError\n",
      "    ConnectionError\n",
      "    BlockingIOError\n",
      "    ChildProcessError\n",
      "    FileExistsError\n",
      "    FileNotFoundError\n",
      "    IsADirectoryError\n",
      "    NotADirectoryError\n",
      "    InterruptedError\n",
      "    PermissionError\n",
      "    ProcessLookupError\n",
      "    TimeoutError\n",
      "    UnsupportedOperation\n",
      "    itimer_error\n",
      "    herror\n",
      "    gaierror\n",
      "    SSLError\n",
      "    Error\n",
      "    SpecialFileError\n",
      "    ExecError\n",
      "    ReadError\n",
      "    URLError\n",
      "    BadGzipFile\n",
      "\n",
      "\n",
      "ImportError\n",
      "    ModuleNotFoundError\n",
      "    ZipImportError\n",
      "\n",
      "\n",
      "IndentationError\n",
      "    TabError\n",
      "\n",
      "\n",
      "IndexError\n",
      "\n",
      "\n",
      "InterruptedError\n",
      "    InterruptedSystemCall\n",
      "\n",
      "\n",
      "IsADirectoryError\n",
      "\n",
      "\n",
      "KeyError\n",
      "    NoSuchKernel\n",
      "    UnknownBackend\n",
      "\n",
      "\n",
      "LookupError\n",
      "    IndexError\n",
      "    KeyError\n",
      "    CodecRegistryError\n",
      "\n",
      "\n",
      "MemoryError\n",
      "\n",
      "\n",
      "ModuleNotFoundError\n",
      "\n",
      "\n",
      "NameError\n",
      "    UnboundLocalError\n",
      "\n",
      "\n",
      "NotADirectoryError\n",
      "\n",
      "\n",
      "NotImplementedError\n",
      "    ZMQVersionError\n",
      "    StdinNotImplementedError\n",
      "\n",
      "\n",
      "OSError\n",
      "    ConnectionError\n",
      "    BlockingIOError\n",
      "    ChildProcessError\n",
      "    FileExistsError\n",
      "    FileNotFoundError\n",
      "    IsADirectoryError\n",
      "    NotADirectoryError\n",
      "    InterruptedError\n",
      "    PermissionError\n",
      "    ProcessLookupError\n",
      "    TimeoutError\n",
      "    UnsupportedOperation\n",
      "    itimer_error\n",
      "    herror\n",
      "    gaierror\n",
      "    SSLError\n",
      "    Error\n",
      "    SpecialFileError\n",
      "    ExecError\n",
      "    ReadError\n",
      "    URLError\n",
      "    BadGzipFile\n",
      "\n",
      "\n",
      "OverflowError\n",
      "\n",
      "\n",
      "PermissionError\n",
      "\n",
      "\n",
      "ProcessLookupError\n",
      "\n",
      "\n",
      "RecursionError\n",
      "\n",
      "\n",
      "ReferenceError\n",
      "\n",
      "\n",
      "RuntimeError\n",
      "    RecursionError\n",
      "    NotImplementedError\n",
      "    _DeadlockError\n",
      "    BrokenBarrierError\n",
      "    BrokenExecutor\n",
      "    SendfileNotAvailableError\n",
      "    ExtractionError\n",
      "    VariableError\n",
      "\n",
      "\n",
      "SyntaxError\n",
      "    IndentationError\n",
      "\n",
      "\n",
      "SystemError\n",
      "    CodecRegistryError\n",
      "\n",
      "\n",
      "TabError\n",
      "\n",
      "\n",
      "TimeoutError\n",
      "\n",
      "\n",
      "TypeError\n",
      "    FloatOperation\n",
      "    MultipartConversionError\n",
      "\n",
      "\n",
      "UnboundLocalError\n",
      "\n",
      "\n",
      "UnicodeDecodeError\n",
      "\n",
      "\n",
      "UnicodeEncodeError\n",
      "\n",
      "\n",
      "UnicodeError\n",
      "    UnicodeEncodeError\n",
      "    UnicodeDecodeError\n",
      "    UnicodeTranslateError\n",
      "\n",
      "\n",
      "UnicodeTranslateError\n",
      "\n",
      "\n",
      "ValueError\n",
      "    UnicodeError\n",
      "    UnsupportedOperation\n",
      "    JSONDecodeError\n",
      "    SSLCertVerificationError\n",
      "    Error\n",
      "    UnsupportedDigestmodError\n",
      "    IllegalMonthError\n",
      "    IllegalWeekdayError\n",
      "    ParserError\n",
      "    ClassNotFound\n",
      "    ClipboardEmpty\n",
      "    MessageDefect\n",
      "    MacroToEdit\n",
      "    InvalidFileException\n",
      "    UnequalIterablesError\n",
      "    InvalidVersion\n",
      "    _InvalidELFFileHeader\n",
      "    InvalidWheelFilename\n",
      "    InvalidSdistFilename\n",
      "    InvalidSpecifier\n",
      "    InvalidMarker\n",
      "    UndefinedComparison\n",
      "    UndefinedEnvironmentName\n",
      "    InvalidRequirement\n",
      "    InvalidVersion\n",
      "\n",
      "\n",
      "ZeroDivisionError\n",
      "    DivisionByZero\n",
      "    DivisionUndefined\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy():\n",
    "    \"\"\"\n",
    "    Prints the Python Exception Hierarchy.\n",
    "    \"\"\"\n",
    "    for exc in dir(__builtins__):\n",
    "        if \"Error\" in exc:\n",
    "            print(exc)\n",
    "            try:\n",
    "                for subexc in getattr(__builtins__, exc).__subclasses__():\n",
    "                    print(\"    {}\".format(subexc.__name__))\n",
    "            except TypeError:\n",
    "                pass\n",
    "            print(\"\\n\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print_exception_hierarchy()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6341d546-3382-4a5e-aea1-63f78bd3fc61",
   "metadata": {},
   "source": [
    "## Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "86e248d9-bc57-43e9-b2dd-c8f48d85cb74",
   "metadata": {},
   "source": [
    "## ANS  ==\n",
    "The ArithmeticError class is a built-in exception class in Python that is raised when an arithmetic operation fails. This exception is a base class for all built-in exceptions that occur for numeric calculation errors."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "66998724-db72-41d4-bec5-952142bf0d0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "## 1. ZeroDivisonError:- This error is raised when attempting to divide by zero. For Example:-\n",
    "x = 10\n",
    "y = 0\n",
    "z = x/y\n",
    "ZeroDivisionError: division by zero"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d24a3a92-52a6-4654-81f1-fbe08160ee7f",
   "metadata": {},
   "outputs": [],
   "source": [
    "## 2. OverflowError: This error is raised when the result of an arithmetic operation is too large to be represented. For example:\n",
    "import sys \n",
    "x = sys.maxsize\n",
    "y = 2\n",
    "z = x*y\n",
    "OverflowError: integer overflow"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7ea4b2e5-48ad-46ff-9bd7-98585007c554",
   "metadata": {},
   "source": [
    "## Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ebf5ab8f-f86a-4898-9771-c62166f63fa7",
   "metadata": {},
   "source": [
    "## ANS ==\n",
    "The LookupError class is used to represent an error that occurs when trying to access an element in a sequence or a mapping using an invalid index or key."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "26435ada-43b2-4b9c-b3bb-5cf2244e4b6f",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'pear'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m## 1. KeyError is raised when trying to access a dictionary using a key that does not exist in the dictionary. for example:-\u001b[39;00m\n\u001b[1;32m      2\u001b[0m my_dict \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mapple\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m1\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mmango\u001b[39m\u001b[38;5;124m'\u001b[39m : \u001b[38;5;241m2\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mpapaya\u001b[39m\u001b[38;5;124m'\u001b[39m : \u001b[38;5;241m3\u001b[39m}\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_dict\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mpear\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m)\n",
      "\u001b[0;31mKeyError\u001b[0m: 'pear'"
     ]
    }
   ],
   "source": [
    "## 1. KeyError is raised when trying to access a dictionary using a key that does not exist in the dictionary. for example:-\n",
    "my_dict = {'apple': 1, 'mango' : 2, 'papaya' : 3}\n",
    "print(my_dict['pear'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "74aa785f-245e-4d7e-afce-7b6969074386",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[10], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m## 2. IndexError is raised when trying to acess a sequenvce using an index that is out of range.For example:\u001b[39;00m\n\u001b[1;32m      2\u001b[0m my_list \u001b[38;5;241m=\u001b[39m [\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m2\u001b[39m,\u001b[38;5;241m3\u001b[39m]\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmy_list\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m3\u001b[39;49m\u001b[43m]\u001b[49m)\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "## 2. IndexError is raised when trying to acess a sequenvce using an index that is out of range.For example:\n",
    "my_list = [1,2,3]\n",
    "print(my_list[3])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8b4a324d-fc07-494c-a9c4-0f664a26d6f0",
   "metadata": {},
   "source": [
    "## Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0670af28-ca6e-45e3-9eed-947cabe70085",
   "metadata": {},
   "source": [
    "## ANS ==\n",
    "In Python, an ImportError is an error that occurs when the Python interpreter is unable to locate and load a module that is required by a program. This can happen for several reasons, including when the module name is misspelled, when the module file is missing or has been moved, or when the module requires another module that is not installed on the system.\n",
    "\n",
    "ModuleNotFoundError, introduced in Python 3.6, is a subclass of ImportError. It is raised when the Python interpreter cannot find the module specified by the import statement. This error occurs when the module is not installed on the system, or when the module file is not present in the specified search path."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8d0a46cc-1b60-46e0-8d0d-4c6ab476b8d7",
   "metadata": {},
   "source": [
    "## Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4833a017-7655-46cd-b47c-d039c1645c82",
   "metadata": {},
   "source": [
    "## ANS ==\n",
    "1. Catch only the exceptions you expect: When writing exception handling code, it is important to catch only the specific exceptions that you expect to occur. Catching too many exceptions can make it harder to identify and debug issues.\n",
    "2. Use try-except-finally blocks: Use try-except-finally blocks to handle exceptions. The try block contains the code that might raise an exception, the except block handles the exception if one occurs, and the finally block contains code that will always be executed, regardless of whether an exception occurred.\n",
    "3. Provide helpful error messages: When raising an exception or handling an exception, provide an informative error message that describes the issue. This makes it easier for developers to debug issues.\n",
    "4. Avoid using bare except clauses: Avoid using bare except clauses as they catch all exceptions, including system-level exceptions that could indicate a serious issue with the program or system.\n",
    "5. Use built-in exceptions: Use built-in exceptions whenever possible, rather than creating your own custom exceptions. This makes it easier for other developers to understand your code and reduces the chance of naming conflicts. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c8891c36-4702-45ac-b44f-8a115dc4d162",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
